"""Intitial revision

Revision ID: ab2ebda871b0
Revises: f479f883e90e
Create Date: 2025-12-24 05:27:35.865978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab2ebda871b0'
down_revision: Union[str, Sequence[str], None] = 'f479f883e90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'driver_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'driver_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
