"""Update

Revision ID: c3cbaabfcca1
Revises: 
Create Date: 2025-12-26 21:32:33.925399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3cbaabfcca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.add_column('users', sa.Column('user_type', sa.Enum('PASSENGER', 'DRIVER', name='user_type'), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'user_type')
    op.alter_column('drivers', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
