"""Intitial revision

Revision ID: f479f883e90e
Revises: 
Create Date: 2025-12-24 05:10:23.880953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f479f883e90e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('brand', sa.String(length=20), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(length=10), nullable=False),
    sa.Column('sts_series', sa.String(length=15), nullable=False),
    sa.Column('sts_number', sa.String(length=15), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('passport_number', sa.String(length=15), nullable=False),
    sa.Column('passport_photo', sa.String(length=50), nullable=False),
    sa.Column('drive_exp', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=10), nullable=False),
    sa.Column('license_series', sa.String(length=10), nullable=False),
    sa.Column('license_photo_1', sa.String(length=50), nullable=False),
    sa.Column('license_photo_2', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=35), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('drivers')
    op.drop_table('cars')
    # ### end Alembic commands ###
