"""Little changes

Revision ID: fa94ac24f47e
Revises: cab44ed620d2
Create Date: 2025-12-25 01:06:02.158039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa94ac24f47e'
down_revision: Union[str, Sequence[str], None] = 'cab44ed620d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('car_class', sa.Enum(), nullable=True))
    op.add_column('cars', sa.Column('photo', sa.String(), nullable=False))
    op.add_column('cars', sa.Column('video', sa.String(), nullable=False))
    op.add_column('cars', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.alter_column('cars', 'sts_series',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.create_foreign_key(None, 'cars', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.alter_column('cars', 'sts_series',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.drop_column('cars', 'user_id')
    op.drop_column('cars', 'video')
    op.drop_column('cars', 'photo')
    op.drop_column('cars', 'car_class')
    op.drop_column('cars', 'model')
    # ### end Alembic commands ###
